---
  detectors:
    IrresponsibleModule:
      enabled: false
    UtilityFunction:
      enabled: false
    UncommunicativeVariableName:
      enabled: false
  exclude_paths:
    - _snippets
    - spec/fixtures/stock_info.rb # one-time test fixture creator
    - spec/fixtures/project_info.rb # one-time test fixture creator