---


development:
  DB_FILENAME: app/infrastructure/database/local/dev.db
  GOOGLENEWS_TOKEN: <personal_access_token>

test:
  DB_FILENAME: app/infrastructure/database/local/test.db
  GOOGLENEWS_TOKEN: <personal_access_token>

production:
  GOOGLENEWS_TOKEN: <personal_access_token>