---
# Name your file secrets.yml

development:
  DB_FILENAME: app/infrastructure/database/local/dev.db
  GOOGLENEWS_TOKEN: <personal_access_token_for_google_news_api>

test:
  DB_FILENAME: app/infrastructure/database/local/test.db
  GOOGLENEWS_TOKEN: <personal_access_token_for_google_news_api>

production:
  GOOGLENEWS_TOKEN: <personal_access_token_for_google_news_api>